name: TKRPGProximityChat
version: ${project.version}
main: org.tomkayrp.tkrpgproximitychat.TKRPGProximityChat
api-version: 1.15
authors: [TKDevTeam]
description: Allows chatting only if another player is in a certain distance.
website: 92.118.16.112:25585
commands:
  proxy:
    description: Help menu for TKRPGProximityChat
    usage: /<command>
    aliases: [proximity, prox]
